# 📁 Save this as: .github/workflows/build-aab.yml
name: Build ZenFit AI AAB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Debug AAB
      run: ./gradlew bundleDebug
    
    - name: Build Release AAB
      run: ./gradlew bundleRelease
    
    - name: Upload Debug AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-aab
        path: app/build/outputs/bundle/debug/app-debug.aab
    
    - name: Upload Release AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-release-aab
        path: app/build/outputs/bundle/release/app-release.aab
    
    - name: Upload mapping file
      uses: actions/upload-artifact@v3
      with:
        name: mapping
        path: app/build/outputs/mapping/release/mapping.txt